### ISSUE TITLE
translation help

### ISSUE THREAD

**Issue by perdolka** [gcp/wxif#13]
Hi. 
I'm trying to make a technically accurate translation of the addon into 2 languages. 
I don't understand the meaning of some lines:

204 - **Transpose**
212 - **Transverse**
220 - **Infinite** _- Focus to infinity ?_
264 - **none** _- It's about white balance preset?_
412 - **no TZ**  _- Time zone did not set ?_

320 - **return light not detected**
324 - **return light detected**
_- It's about TTL, as I know._

**Comment by Eagle3386** [comment]
> Hi.
I'm trying to make a technically accurate translation of the addon into 2 languages.
I don't understand the meaning of some lines:

Hey, @perdolka, from what I read and understand, the answers are:
> 204 - Transpose
212 - Transverse

As the [man page for jpegtran](https://www.commandlinux.com/man-page/man1/jpegtran.1.html) states:
- flip horizontal = mirror image horizontally (left-right)
- flip vertical = mirror image vertically (top-bottom)
- (...)
- transpose = transpose image (across upper-left to lower-right axis)
- transverse = transverse transpose (across upper-right to lower-left axis)

So, **transpose** is kind of a **[flip-rotate combination](https://en.wikipedia.org/wiki/Transpose)**, e. g. for turning a landscape picture into portrait mode.
And transverse is like transpose, but instead of upper-left -> lower-right, it's upper-right -> lower-left.

> 220 - Infinite - Focus to infinity ?

Correct.
> 264 - none - It's about white balance preset?

Correct. No WB preset set.
> 412 - no TZ - Time zone did not set ?

Correct. No TZ was provided, i. e. not set by the photographer.

> 320 - return light not detected
324 - return light detected

It means that the flash's emitted light was detected as being returned to the sensor (324) or not (320).

HTH,
 Martin

**Comment by perdolka** [comment]
Thanks for the explanation.

**Comment by Eagle3386** [comment]
Just give me a +1, that's enough. :wink:

**Comment by Eagle3386** [comment]
@gcp, as I can't add labels nor assign issues, please consider this as a reminder to close this issue as fixed. 😃
